# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b348a362a0321a74ffb7d6a24614f469d3ce9d5cb7e45a83ac11b2a6cf0278fd7776c2c5f2796c030fcd566e29243899ed384cd0c0ee72680e37f673202d2e

test:
  secret_key_base: 54f72a7077e4eda579eefd64dfdc4986d4fd491208ead22a49e982c1696ed5ca0f9ef956fe5af732e2164f2a2fe00a09bcd9566a61efaa213709d840eab63525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
